"""
Loader for the 4-input NPN template database.

The actual data lives in ``aig_db_4.pkl`` (binary pickle, ~2 MB, gitignored),
generated by :mod:`nand_optimizer.precompute_4cut`.  The bootstrap in
:mod:`nand_optimizer.__init__` triggers regeneration when the pickle is
missing.

This module exposes :data:`AIG_DB_4` lazily: the pickle is loaded on first
attribute access so that ``import nand_optimizer.aig_db_4`` stays cheap and
``grep``/IDEs see only a handful of lines where a 5.7 MB Python dict
literal used to live.
"""

from __future__ import annotations
import os
import pickle
from typing import Dict, List, Tuple

_DB_PATH = os.path.join(os.path.dirname(__file__), "aig_db_4.pkl")
_CACHE: Dict[int, Tuple[int, List[Tuple[int, int]]]] | None = None


def _load() -> Dict[int, Tuple[int, List[Tuple[int, int]]]]:
    global _CACHE
    if _CACHE is None:
        with open(_DB_PATH, "rb") as f:
            _CACHE = pickle.load(f)
    return _CACHE


def __getattr__(name: str):
    if name == "AIG_DB_4":
        return _load()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
