"""
Loader for the 4-input XAG (XOR-AND Graph) template database.

The actual data lives in ``xag_db_4.pkl`` (binary pickle, ~2 MB, gitignored),
generated by :mod:`nand_optimizer.precompute_xag_db`.  The bootstrap in
:mod:`nand_optimizer.__init__` triggers regeneration when the pickle is
missing.

This module exposes :data:`XAG_DB_4` lazily: the pickle is loaded on first
attribute access so that ``import nand_optimizer.xag_db_4`` stays cheap.

Entry format: db[tt] = (out_lit, ops)
  ops is a list of (a_lit, b_lit, op_kind) triples
  where op_kind 0 = AND, 1 = XOR.
"""

from __future__ import annotations
import os
import pickle
from typing import Dict, List, Tuple

_DB_PATH = os.path.join(os.path.dirname(__file__), "xag_db_4.pkl")
_CACHE: Dict[int, Tuple[int, List[Tuple[int, int, int]]]] | None = None


def _load() -> Dict[int, Tuple[int, List[Tuple[int, int, int]]]]:
    global _CACHE
    if _CACHE is None:
        with open(_DB_PATH, "rb") as f:
            _CACHE = pickle.load(f)
    return _CACHE


def __getattr__(name: str):
    if name == "XAG_DB_4":
        return _load()
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
